version: '2.0'

services:
    polr:
        image: kelvinneves/docker-polr
        container_name: polrlink
        ports:
            - "80:80"

    mariadb:
        image: mariadb
        container_name: mariabanco
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=polr
          - MYSQL_USER=polr_admin
          - MYSQL_PASSWORD=polr_admin
        volumes:
          - /var/lib/mysql
